### ISSUE TITLE
[BUG] Panic-ked at 'assertion failed: max_phys_addr < (1 << 48) / 512'

### ISSUE THREAD

**Issue by Stay1444** [LibertyOS-Development/kernel#19]
**Describe the bug**
After running `cargo run --release` i get `panicket at 'assertion failed: max_phys_addr < (1 << 48) / 512'` (build success, and running in QEMU)

**To Reproduce**
1. Clone the repo
2. run it in releasemode

**Expected behavior**
The system boots

**Screenshots**
![image](https://github.com/LibertyOS-Development/kernel/assets/36738990/0f835c52-b339-4b47-a1bf-4b670d42231d)

**Additional information**
 - Architecture: x86_64
 - OS: Arch Linux Kernel 6.4.1
 - Build environment: linux
 - QEMU version: QEMU emulator version 8.0.2
 - rustc version: rustc 1.59.0-nightly (cfa4ac66c 2022-01-06)
 - Commit hash: 8daca65787c258baebcc0a3f3b38bd0bc8ce7d7e

**Comment by tomshoo** [comment]
This apparently is a bug in the [bootloader](https://github.com/rust-osdev/bootloader) crate, which was mentioned in issue [#1138](https://github.com/phil-opp/blog_os/issues/1138), which is apparently fixed in its pull request [#234](https://github.com/rust-osdev/bootloader/pull/264). I currently have a [branch](https://github.com/tomshoo/kernel/tree/nightly-2023-07-04) that bumps up everything to the latest, and apparently, everything seems to work just fine the system seems to boot, but I still am a tad hesitant to create a PR because bumping everything to the latest might just open another can of worms.

**Comment by Stay1444** [comment]
Amazing! Will check it out and see if i can contribute. Any recommendations?

**Comment by tomshoo** [comment]
> Any recommendations?

I just tested it on an older toolchain and seems like bumping the version for `bootloader` crate to `0.9.23` seems to be enough. You can try doing that and testing even further. I unfortunately cannot ATM since it is 12:00AM here and I need to get some sleep.

**Comment by tomshoo** [comment]
This issue has been fixed in PR #25.

**Comment by danielteberian** [comment]
Thank you @tomshoo. I'm closing this issue.
